### ISSUE TITLE
Provider does not return package resource information

### ISSUE THREAD

**Issue by sudodevnull** [Tripwire/puppet-te_agent#8]
The update to self.instances to remove the puppet resource package error, does not return valid package resource information.

**Comment by bespokebob** [comment]
True, but does it need to? The agent package should only be managed inside this module. Why do you need the resource command to return the agent information?

**Comment by sudodevnull** [comment]
It should, as it is an installed package. It is only managed inside the module.  Why don't you want your custom provider to work properly?

**Comment by bespokebob** [comment]
The "real" installed package is a native OS package (rpm, deb, etc.), and will show up (as TWAgent or something similar) under that provider. It would be somewhat redundant for the custom provider to also report the package as installed.

I just don't understand exactly why you need the provider to report something with the "resource" command. What are you trying to do with this information? If you are trying to get an inventory of installed packages, then the resource command should already report the native package as being installed (assuming the other issue - the missing self.instances method - is fixed). If you are trying to turn the output of the "resource" command into a manifest to use in some way, then you will have difficulty managing the package outside of this module (as you'll need all the extra command-line arguments as well).

**Comment by sudodevnull** [comment]
Then why have the custom provider at all? Is the version returned in my update not the version of tripwire installed?? If it's a native OS package, why not write a package manifest and use a package resource to manage it instead of a custom provider?  Would it be better if I re-wrote the module to use a standard package resource to eliminate the custom provider completely?

**Comment by bespokebob** [comment]
The custom provider just makes the `install.pp` manifest simpler. The installer on non-Windows OS is provided as an executable `.bin` file that is a wrapper around the native package, and an `uninstall.sh` script that handles removing it. It could probably be handled differently with several command resources and maybe a custom fact, but it would be a bit messy, and need to be handled differently on Windows. The package provider gives the exact interface needed to handle installing a package in a non-standard way, so that's what I went with.

**Comment by sudodevnull** [comment]
Is the version returned in my update not the version of tripwire installed?

**Comment by joshsleeper** [comment]
@sudodevnull I don't think @youngbob has an issue with the custom provider working properly.
I think he's just looking to understand exactly what you're trying to do, and how #7 resolves that problem for you.

Reading through both this issue and the PR, I'm also confused about what the goal is.
Can you try to clearly spell out both the problem you want to solve as well as your use case where this problem is affecting you?

**Comment by sudodevnull** [comment]
When you run 'puppet resource package' on a node, it does not return the package information. Adding this adds the package and version.

**Comment by bespokebob** [comment]
As I already explained, the "resource" command does, in fact, return the package information. It returns the native packages that are installed by the .bin installer. I don't see why you need an additional resource listed for the .bin installer, since it isn't the real package that is installed.

**Comment by sudodevnull** [comment]
This module inserts a provider for the package type.  The package type defines a version property, defined by puppet. This provider does not return that value.  My update gets the valid version property, and returns it like a package provider should.  It should be able to return and/or enforce a version.  Without the version value in the provider, that cannot be done.  We want to know that the version that is managed by this provider, is valid, so that it can be maintained.

**Comment by sudodevnull** [comment]
Also, please validate your claim. When I run puppet resource package, I do not see this twagent or anything similar listed.  When I run the same command with my additions added into your module, i get the following package added to the list:
package { 'teagent-realtime':
  ensure => '0.9-1.el6.5',
}

Please run puppet resource package, on a rhel6 (just as an example) node and tell me what the package name that is returned without my additions.  Thank you.

**Comment by bespokebob** [comment]
After installing the agent on my CentOS 7 box, and without your changes, I have:

```puppet
package { 'TWeagent':
  ensure => '8.5.3-0',
}

package { 'teagent-realtime':
  ensure => '0.9-el7.3',
}
```

The first package is the main agent package, which is I think is exactly what you're looking for.

**Comment by sudodevnull** [comment]
Maybe it's a rhel 6 thing then.  I did not see either of those until my addition to your module.

**Comment by bespokebob** [comment]
There doesn't seem to be any possible way that your change could have caused a package named `teagent-realtime` to appear, since your change will only ever return a package named `te_agent`, and because `teagent-realtime` is an installed rpm. You should be able to see both packages installed with `rpm -qa | grep agent`. If Puppet is not returning all installed rpms for some reason, it is not an issue with this module.

And as I have already said before, the custom provider is only intended to be used inside this module. If there were some way to make it "private", then I would. There should be no reason to try to use it directly. If you want to enforce a version of the agent, you can do that through the module already.
